---
title: "Mini-Project 4"
author: "Zane Shango"
date: "4/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
library(dplyr)
library(scales)

setwd("~/PLS397/mini_project4")

```



## Format Data into Edges and Nodes
```{r}
load("nigeriaData")

# create edges df with renamed variables
ng_edges <- nigeriaData %>%
  rename(source = Var1, target = Var2, conflict = value, year = L1)


# get unique source and target actors 
uniq_s <- unique(ng_edges$source)
uniq_t <- unique(ng_edges$target)
# are they equal to each other? (result is TRUE, they are equal to each other) 
# all_equal(uniq_s, uniq_t)
uniq_orgs <- unique(ng_edges$source)
  
id <- 1:length(uniq_s)

# create nodes df
ng_nodes <- as.data.frame(uniq_orgs)
ng_nodes <- cbind(ng_nodes, id) # add id variable
names(ng_nodes) <- c("actor", "ID") # rename nodes column headers 

```

<P style="page-break-before: always">

## Add Weights and Create Graph Object
```{r}
# need to adjust the edges df so it has weights
# make the edges df cumulative conflict over the years rather than yes no conflict each year

# for each source of conflict their total years conflicting with each target
ng_edges_weight <- ng_edges %>%
  select(source, target, conflict) %>%
  group_by(source, target) %>%
  summarise_all(sum)
# filter out pairs of sources and targets that had zero conflicts
ng_edges_weight <- ng_edges_weight %>%
  filter(conflict !=0)

# graph from the df, directed is TRUE because the conflict has sources and targets
ng_g <- graph_from_data_frame(d = ng_edges_weight, vertices = ng_nodes, directed = TRUE)
# set weights manually
ng_g <- set_edge_attr(ng_g, "weight", value = ng_edges_weight$conflict)
# check to make sure ng_g is weighted, TRUE so it is
# is_weighted(ng_g)

```

<P style="page-break-before: always">

## Data Wrangling for Custom Sizes
Sizes will be based on each organizations number of conflicts.
```{r}

# size of nodes, can be based on the total number of conflicts occurred with an organization (could be source or target of conflict) 
# need to get the total number of years with conflict for each organization regardless of source/target
# create two summary tables one grouped by source, and one by target, with total conflict of each organization
source_conf <- ng_edges_weight %>%
  group_by(source) %>%
  summarize(
    source_conflicts = sum(conflict)
  ) %>%
  rename(organization = source)


source_conf

target_conf <- ng_edges_weight %>%
  group_by(target) %>%
  summarize(
    target_conflicts = sum(conflict)
  ) %>%
  rename(organization = target)


target_conf


# want to join these two dataframes to get the true total conflicts, regardless of source/target position
# full_join() puts NA for orgs that don't appear in one of the datasets as their source/target value
# change NAs to zeros to ensure the total column adds up correctly
conflicts <- full_join(source_conf, target_conf, by = "organization", keep = TRUE)
conflicts$source_conflicts[is.na(conflicts$source_conflicts)] <- 0
conflicts$target_conflicts[is.na(conflicts$target_conflicts)] <- 0

# create a new column in conflicts, that sums the source and target conflicts to get a count of total conflicts for each organization
conflicts <- conflicts %>%
  mutate(
    total_conflicts = source_conflicts + target_conflicts
  )


```

<P style="page-break-before: always">

## Add Vertex and Edge Attributes
```{r}
# need to get orgs and total conflicts into named vector format to add it as a column for V()
confs <- as.numeric(conflicts$total_conflicts)
names(confs) <- conflicts$organization
confs <- log(confs +1)

# now set total confs as the size variable for vertex attributes
V(ng_g)$size = confs

# only put organization name on the node if they had 5+ years with conflicts since 1997
V(ng_g)$label = ifelse(
  confs > 2,
  V(ng_g)$name,
  NA
)

# add width of edges
E(ng_g)$width = log(E(ng_g)$weight + 1)


# set color of nodes that are primarily sources red, primarily targets blue, undecided or other as black
# need to do manually
# red = primarily source
# blue = primarily target
# green = Nigerian police/military
# grey = neutral 
# category is determined by a >= 3 difference in either direction makes you primarily that side
# is less than 3 you are neutral, unless you have a 0 in one side then youre categorized as the one with values

V(ng_g)$color = c('grey', 'blue', 'grey', 'red', 'grey', 'red' ,'blue' ,'blue', 'red', 'green', 'red', 'green',
                  'grey', 'blue', 'grey', 'grey', 'grey', 'grey', 'red', 'grey', 'grey', 'grey', 'grey', 'blue',
                  'red', 'grey', 'grey', 'grey', 'grey', 'blue', 'red', 'grey', 'grey', 'blue', 'blue', 'blue',
                  'blue')


```


<P style="page-break-before: always">

## Plot
```{r}
# plot network 
# rescale for visualization
V(ng_g)$nodeSize = rescale(V(ng_g)$size, to=c(1, 25))

#par(mar=c(0,0,0,0))
set.seed(23)
plot.igraph(
  ng_g,
  layout = layout_with_fr,
  vertex.color = V(ng_g)$color, # changes the color of the nodes
  vertex.size = V(ng_g)$nodeSize, # controls the sizing of the nodes
  vertex.label = V(ng_g)$label, # controls what text is displayed on the nodes
  vertex.label.color = 'black', # changes the color of the label text
  vertex.label.cex = .35, # change size of labels to 50% of original scale
  edge.curved = .25, # controls level of curving to dataset (25%)
  edge.color = 'grey20',
  edge.width = E(ng_g)$width, # assigns edge width
  edge.arrow.size = .18, # controls arrow size (18%)
  main = "Nigerian Conflict",
  xlim = c(0,.25),
  ylim = c(-.9,.9)
)
```






